applications:
- api_domain: api.staging.jit.io
  application_name: aaa
  auth_header_name: sads
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.api_scan_authentication_value }}
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
github_branch_protection:
  organization:
    amount_of_required_reviews: 2
    required_status_checks: []
resource_management:
  exclude:
    plan_items:
      item-secret-detection:
        resources:
          - name: test-prod
            type: repo
