applications:
- api_domain: api.staging.jit.io
  application_name: zap-stg
  authentication_key: Authorization
  authentication_mode: header-bearer
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
github_branch_protection:
  organization:
    amount_of_required_reviews: 2
    required_status_checks: []
resource_management:
  runner_config:
    job_setup_timeout_minutes: 15
    job_execution_timeout_minutes: 40
    pr_job_setup_timeout_minutes: 15
    pr_job_execution_timeout_minutes: 30
  exclude:
    plan_items:
      item-secret-detection:
        resources:
          - name: test-prod
            type: repo


